### ISSUE TITLE
Generating Population II and III Stars

### ISSUE THREAD

**Issue by Tristoncg** [cschreib/ifni#1]
I haven't come across anything in the documentation that directly addresses Population II and Population III stars, but I am interested in generating mock galaxies using one or both of these Populations.

Is E.G.G. capable of handling this tasks, and if so which parameters/catalogs would need to be modified to produce either of these Populations of stars?

I have no formal astrophysics education, but I understand that these early stars had little to no metalicity. From the --help command, I noticed the IGM string that can be set, but I am not convinced I'm looking in the right area.

**Comment by cschreib** [comment]
Hi and thank you for your interest in EGG! Unfortunately at present there is no support for population II or III stars in EGG. I am not very familiar with the literature on this topic, so I wouldn't even know how to generate them. My understanding is that this is still mostly unknown, and not constraint by observations. For example, we don't know at what epoch they existed, in what numbers, and what their spectra would look like. I think this has been predicted by some numerical simulations, but not observed yet. Perhaps soon with JWST! 

Let me know if you have other questions.

**Comment by Tristoncg** [comment]
You're spot on about them being mostly unknown and hopefully JWST reveals some details! There are some observed Population II stars, such as Methuselah (HD 140283). 

Do the current procedures for generation factor in dispersal of metals, such as supernovae or neutron mergers, when constructing stars? I'm interested in the process of metal seeding occurring in the interstellar medium of proto-stellar discs, or even the IGM. My interest seems to be quite niche or lacking observational research so I totally understand if it is beyond the scope of E.G.G.

**Comment by cschreib** [comment]
EGG is a very simple tool, it actually contains very little physics. Most of what it does is based on observed empirical relations. For example, the metallicity of a galaxy in the simulation is just "guesstimated" based on a known average relationship between metallicity and the galaxy's mass and star formation rate.
Another example: there's no notion of "time" in the simulation. Galaxies don't grow, they are constructed fully formed in a single "time step".

Based on your last paragraph, I think you might find other simulation tools more interesting, such as those that run actual physics-based simulations from first principles (such as Illustris, Eagle, ...). Or maybe semi-analytic models.

**Comment by Tristoncg** [comment]
Got it. I was okay with a single point in time, but I wasn't really sure what went on under the hood. I appreciate you taking the time to answer my questions and give me a couple other suggestions!
